<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Previous</name>
   <tag></tag>
   <elementGuidId>8f244743-ea73-4184-ab06-fb21e2c57d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatableCustom_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatableCustom_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00e4ba31-b650-46ea-a7a7-05db091f06ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>816e876b-ab1b-49b7-ab9c-cd4a542cec76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatableCustom_previous</value>
      <webElementGuid>560772db-43eb-451b-95a3-7057cc1322c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>af3a2401-d0b9-408a-a42c-6262d1544c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustom_previous&quot;)</value>
      <webElementGuid>2793a4f3-6fde-4263-836a-65755c0f54ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatableCustom_previous']</value>
      <webElementGuid>f206ecbb-9eac-460c-b68a-098b59d296fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableCustom_paginate']/ul/li</value>
      <webElementGuid>97dd52ad-6e82-4103-a5ba-c0b31bfd2392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 50 of 6,675 entries'])[1]/following::li[1]</value>
      <webElementGuid>04ad4d14-b748-49e7-ae9f-2bcb03824a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total'])[1]/following::li[1]</value>
      <webElementGuid>22a81721-2569-4ae4-9e2c-3aecd805efed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[9]</value>
      <webElementGuid>877afde3-731c-404b-a17a-6209f3fcc341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[9]</value>
      <webElementGuid>18a8d080-29b8-4edb-ad39-2e7d990f69cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li</value>
      <webElementGuid>d17512df-42bd-46fe-8a9f-ace1823ef5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatableCustom_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>b8d33252-1c9b-4a8a-868c-1ed36ceb06e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
