<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Next</name>
   <tag></tag>
   <elementGuidId>47d09ce2-2816-4668-a0f5-22c00e8c5546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatableCustom_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datatableCustom_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>120dff75-440f-487b-ac01-6cd22aa3acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>23e4e9d7-b931-4fdc-ade8-3b58096e6bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatableCustom_next</value>
      <webElementGuid>338659f1-6ae3-4cdc-9de6-d4060f881cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>086d57f8-da8a-4171-8bd7-c9f475cdb73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustom_next&quot;)</value>
      <webElementGuid>eeb2d19a-b28a-4e8a-ae24-61f9a4b922f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatableCustom_next']</value>
      <webElementGuid>00c52d6a-03d3-4f77-b287-d0acef7135a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableCustom_paginate']/ul/li[2]</value>
      <webElementGuid>96b026d7-493c-484e-b0df-91d78d46871b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries'])[1]/following::li[2]</value>
      <webElementGuid>8982f9e7-d323-4b43-bad5-167536af155e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total'])[1]/following::li[2]</value>
      <webElementGuid>67fd152c-ab65-43fe-aeee-d3fa384e3f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::li[1]</value>
      <webElementGuid>a6b59fae-271c-419c-8a64-02ac358c0483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number Of Shareholder'])[1]/preceding::li[1]</value>
      <webElementGuid>a64af4c2-86d2-4aef-b41d-689e1406511b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li[2]</value>
      <webElementGuid>a4ad29b1-95d5-4615-a54b-ebdf58fe62f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatableCustom_next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>d6c8e39d-ce88-48a1-9e0c-5390de8b804d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
