<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MPU_member_product_username</name>
   <tag></tag>
   <elementGuidId>d312719d-f6fc-4dc1-92a2-9959b39f1578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#member_product_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member_product_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>048aba5c-3000-4174-b6d8-05c1acb2200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06c1043c-98a0-456a-b7df-a8ae96b62224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_product_username</value>
      <webElementGuid>a8961009-49c1-4803-b414-3bb9817f6eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member_product_username</value>
      <webElementGuid>44846bca-5ae2-4186-8344-75fdffeee36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87fb0930-bc1e-492b-add8-9bf6b43f1b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member_product_username&quot;)</value>
      <webElementGuid>078addc8-2ecc-485e-a06a-671136c97696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member_product_username']</value>
      <webElementGuid>060610c8-3b2c-4c4d-a720-694ef9cadffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='memberListLayout']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>d6f40096-7f8f-4f8f-931c-8f9fbc14d778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>06b659a2-fc4d-40ad-a7a3-b457276b8fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'member_product_username' and @id = 'member_product_username']</value>
      <webElementGuid>0ad546e8-ad89-48b1-b9bf-a5a693e3533a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
