<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Commission</name>
   <tag></tag>
   <elementGuidId>80164859-144a-44f5-b811-52b96c599d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatableCustomTop']/thead/tr/th[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>f75e861f-b050-47e6-bc9b-9a267277aec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commission</value>
      <webElementGuid>ae257b62-d556-40be-891f-64c87f6852c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustomTop&quot;)/thead[1]/tr[1]/th[6]</value>
      <webElementGuid>a3be578b-1462-4840-ae60-53357145586c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatableCustomTop']/thead/tr/th[6]</value>
      <webElementGuid>a20e6be9-32ec-4fe8-b913-cd8304b26824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid Sales'])[1]/following::th[1]</value>
      <webElementGuid>49b3dd44-062a-4e46-92e5-0b29b89bc687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::th[2]</value>
      <webElementGuid>84b7847f-2a99-4542-ade3-75647ae41e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game'])[2]/preceding::th[1]</value>
      <webElementGuid>3db9b5e3-a6e5-410c-95f5-670464c740a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payout'])[1]/preceding::th[2]</value>
      <webElementGuid>fa5a3eba-7f37-4ae9-8594-8857a0454caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>a743fcc2-c405-428c-885c-afa05cfad92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Commission' or . = 'Commission')]</value>
      <webElementGuid>f1ede417-3a52-47dc-9810-daa6afafdd7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
