<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Payout</name>
   <tag></tag>
   <elementGuidId>5f698a18-a510-41b4-8de7-4bae15697aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatableCustomTop']/thead/tr/th[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(8)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b051afe0-fa47-4818-9df4-523115660f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payout</value>
      <webElementGuid>22ff16eb-8f17-4720-8f04-4dc7fa5f8fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustomTop&quot;)/thead[1]/tr[1]/th[8]</value>
      <webElementGuid>6a34294f-d239-4c69-89a6-c59a9dc5d4b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatableCustomTop']/thead/tr/th[8]</value>
      <webElementGuid>aa2e30df-928c-4d3a-8d6a-b6d07232cfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game'])[2]/following::th[1]</value>
      <webElementGuid>9d878b72-a1a2-4aab-a5ee-ce33e7ee8dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commission'])[2]/following::th[2]</value>
      <webElementGuid>46ed9d06-8aa7-4e3b-8415-c8bc9cecc49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profit'])[1]/preceding::th[1]</value>
      <webElementGuid>9cad96dd-d4da-4cf1-b42c-4b490f6a696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Win Loss'])[1]/preceding::th[2]</value>
      <webElementGuid>bda71586-cad7-47ec-9d2d-2663b6100c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payout']/parent::*</value>
      <webElementGuid>fe9bde15-da0e-402c-9e84-5480a7d8c44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]</value>
      <webElementGuid>877d09cc-0aef-4017-8bfc-d42e4990b119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Payout' or . = 'Payout')]</value>
      <webElementGuid>2fc81970-1d73-45e5-81cb-69f6d6c489f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
