<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Previous</name>
   <tag></tag>
   <elementGuidId>f09cde41-709e-4409-88ae-d50b01f815e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatableCustom_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatableCustom_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1dc8547d-57aa-44b5-81bd-73445effe499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>b26105aa-399e-4c37-b0d1-a5a241bc7f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatableCustom_previous</value>
      <webElementGuid>7cedf918-f1c7-4c8e-a7ba-15f6ad55738d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>4f9d50b4-7bb9-4f4e-92f4-7f5c73ba0a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustom_previous&quot;)</value>
      <webElementGuid>d6ea89b0-0e78-425a-8dbb-a029b6c19935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatableCustom_previous']</value>
      <webElementGuid>766efa14-bae5-44fd-946f-254b3deb656d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableCustom_paginate']/ul/li</value>
      <webElementGuid>7a1fd9db-8807-46ff-bc38-ae701a87262f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries'])[1]/following::li[1]</value>
      <webElementGuid>05881a67-e39f-4b05-9f7c-29515bd7ba53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total'])[1]/following::li[1]</value>
      <webElementGuid>b70a38c3-4498-46ab-bc0f-47f991762c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[2]</value>
      <webElementGuid>1920d672-f056-43c9-b000-f610bb195e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[2]</value>
      <webElementGuid>aa0f8e22-20a4-4adb-a8ca-38a90eae29dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li</value>
      <webElementGuid>fa203dd3-d338-46be-a97e-582a0b6af79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatableCustom_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>f73a3fc6-8d9a-4755-8758-21de9420d13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
