<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllEgames</name>
   <tag></tag>
   <elementGuidId>f658be0a-7830-4669-852e-86400bc7a6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='winLossMemberReportLayout']/div/div/div[2]/form/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2160ed71-90b8-4d1e-b4bb-d94ff6788868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control category</value>
      <webElementGuid>aa808ad7-9c43-49fb-b946-8efe1599e2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    </value>
      <webElementGuid>e7024355-bba1-407b-80ea-bb4a12e11b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;winLossMemberReportLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__head kt-portlet__head--lg&quot;]/div[@class=&quot;kt-portlet__head-toolbar&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group mb-2 mr-2&quot;]/select[@class=&quot;form-control category&quot;]</value>
      <webElementGuid>70d1804d-b06d-48af-ae2d-1d1392826e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='winLossMemberReportLayout']/div/div/div[2]/form/div/select</value>
      <webElementGuid>7d68a790-9919-416e-be99-90ba7e29d903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category :'])[1]/following::select[1]</value>
      <webElementGuid>d8c27382-2313-4493-950f-b66aa13898c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Win Loss Report'])[2]/following::select[1]</value>
      <webElementGuid>e0bc0b64-8747-4439-baa0-aadb84fa4955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game :'])[1]/preceding::select[1]</value>
      <webElementGuid>2726bb81-c415-4deb-8fec-0009e99b7065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range :'])[1]/preceding::select[2]</value>
      <webElementGuid>7e004c99-3b0f-4896-854a-4919ab39460a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>24655b9e-b0a0-4199-8681-39d5ec8d4a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ' or . = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ')]</value>
      <webElementGuid>b97d5bcc-a790-40f7-9797-6a47a8f69261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
