<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Next</name>
   <tag></tag>
   <elementGuidId>c448e039-ec98-43c7-b9bb-3b635c0b6fb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatableCustom_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datatableCustom_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>30172a10-afe5-4a77-90bf-bce97a01780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>85235277-ca5c-450e-ab8f-346019edbeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatableCustom_next</value>
      <webElementGuid>c5b6c3bb-f04b-4f83-bbce-62d3f86e4c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>a9fa520e-aa16-40dd-9019-b648bb3da303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustom_next&quot;)</value>
      <webElementGuid>a055cc4e-4fbd-4a8a-94ca-7ba56de78c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatableCustom_next']</value>
      <webElementGuid>e9f80f30-7162-4d8c-9f18-fd747727b463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableCustom_paginate']/ul/li[3]</value>
      <webElementGuid>4f93e74e-43ed-4a61-8265-c07b3883a25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 4 of 4 entries'])[1]/following::li[3]</value>
      <webElementGuid>37a2ed8e-e0e8-487d-bc98-4d2d7e0c69fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Redeem List'])[4]/following::li[3]</value>
      <webElementGuid>e3b7ea1c-2b2f-4919-b08c-6e8e8407cd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>d283cd66-c852-4cd6-ac6b-3de104ae46f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[1]</value>
      <webElementGuid>ee1d31b7-ae20-435b-b758-32d95577294e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li[3]</value>
      <webElementGuid>c7dfaac7-223a-43bb-bfe0-d3ee87ab3af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatableCustom_next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>bf0f136c-7c6c-4a57-9c9d-dc005b4dc688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
