<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Previous</name>
   <tag></tag>
   <elementGuidId>ced74675-5058-4d81-b366-59a2b83af3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatableCustom_previous']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datatableCustom_previous</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>20ff67f7-5727-44d7-899b-a3cb4d51e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>6fb0ff15-9943-4839-a7ee-297659ac4f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatableCustom_previous</value>
      <webElementGuid>aba4e990-dff3-480f-a689-52361a315df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>eac98a5c-a9a0-4fd1-989a-c4deba33c75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustom_previous&quot;)</value>
      <webElementGuid>6d9bcd62-1807-4482-b2e6-3fff3e187788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatableCustom_previous']</value>
      <webElementGuid>e263590d-c1b7-476d-8561-286f20dd6ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableCustom_paginate']/ul/li</value>
      <webElementGuid>cc2078ad-7f53-4728-9e57-522c5db1177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 4 of 4 entries'])[1]/following::li[1]</value>
      <webElementGuid>b5a1adf1-f16a-41f7-84b5-9280ff94d3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Redeem List'])[4]/following::li[1]</value>
      <webElementGuid>0c77c4d1-3d7a-4f14-85c7-7e6191a68957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[3]</value>
      <webElementGuid>75b8020e-e528-48bf-b77e-b2f79fd356c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::li[3]</value>
      <webElementGuid>1ff5870f-f75a-4d61-83b2-accb5da3a8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li</value>
      <webElementGuid>199b4a31-831a-4afa-b6ae-196a1d95b4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatableCustom_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>3151e91c-af9f-4a31-aa7e-fc46ff27a18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
