<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_alllkym5tigerhubking1678</name>
   <tag></tag>
   <elementGuidId>e1cf77f7-a945-4fa1-a649-89600b53c3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='changeApptype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#changeApptype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c01051b8-009b-4c9d-afd3-479bd80ce3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeApptype</value>
      <webElementGuid>5341fbf9-9340-475e-990b-5694b458e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>10a7d4e4-a7a6-46b3-b5e5-82e692415744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
															all
															lky
															m5
															tigerhub
															king1678
													</value>
      <webElementGuid>acfa0707-7ed3-4ae7-b2b7-40f76f5ec621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changeApptype&quot;)</value>
      <webElementGuid>f12881e4-a4a1-4d9c-ad64-9abaed8711e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='changeApptype']</value>
      <webElementGuid>b649eff5-99b6-4ceb-b930-0bfc79a483e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='couponListLayout']/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>38da1455-b3f1-423b-bae2-40a09a831fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Type :'])[1]/following::select[1]</value>
      <webElementGuid>d359e6a8-46d0-477c-b8b1-3b847cfd4bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon List'])[3]/following::select[2]</value>
      <webElementGuid>d1ef0101-cba1-4d0d-becb-691b4e432124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::select[1]</value>
      <webElementGuid>3f79e8e5-6e7f-439a-8e7b-60d22597b071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::select[1]</value>
      <webElementGuid>57400ef5-861b-4326-959d-88542e1ab464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a670a4f3-1cb2-47f5-bf55-9d0d3bc47bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'changeApptype' and (text() = '
															all
															lky
															m5
															tigerhub
															king1678
													' or . = '
															all
															lky
															m5
															tigerhub
															king1678
													')]</value>
      <webElementGuid>1134104d-86b8-45c9-9b7b-d986c64a4ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
