<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Win Loss</name>
   <tag></tag>
   <elementGuidId>210992d0-b6b9-4c0f-b3e3-5e5badb6dde2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatableCustomTop']/thead/tr/th[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>e5aab5a2-f598-4180-bfc3-47f8e3ade92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting</value>
      <webElementGuid>f82de201-165b-4bcb-acb5-9cc51e1fd839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa4fcab6-3956-46d5-95e3-3f9c3a9d91f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>datatableCustomTop</value>
      <webElementGuid>b0b0afff-1b4a-40ac-bc55-d0ad8331277f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>58e9dbe5-7c2d-431a-a23c-82b7e01d2159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8b99e5a9-007c-49fe-951c-6ab38a878945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Win Loss: activate to sort column ascending</value>
      <webElementGuid>07901cea-2f13-47aa-bb55-f3cf6c30622d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Win Loss</value>
      <webElementGuid>b9316cab-0c25-4779-aff1-3f579961f595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableCustomTop&quot;)/thead[1]/tr[1]/th[@class=&quot;sorting&quot;]</value>
      <webElementGuid>8f8c33cd-ccf5-4b1c-8bb5-59c8bc5afa05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatableCustomTop']/thead/tr/th[6]</value>
      <webElementGuid>f1fc048e-3dc7-43e2-a1b3-258f7a385be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payout'])[1]/following::th[1]</value>
      <webElementGuid>be424043-3f31-41d1-9a40-42ede4b7217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::th[2]</value>
      <webElementGuid>562ab84b-f6d4-4e82-a3d9-2abd7138b711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settlement'])[2]/preceding::th[1]</value>
      <webElementGuid>b5bc8509-9a03-41be-9043-1ce96f4d365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commission'])[2]/preceding::th[2]</value>
      <webElementGuid>1e2251da-665b-4081-b3c7-7e8bff4cf67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Win Loss']/parent::*</value>
      <webElementGuid>d677cad2-8e0b-4f90-9346-a70f45827cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>2fbcdc30-f8f4-49f2-82da-39b9b705da58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Win Loss' or . = 'Win Loss')]</value>
      <webElementGuid>c1d2c8e1-9b12-4740-a296-95cc6572ccad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
