<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllEgames</name>
   <tag></tag>
   <elementGuidId>ef968615-b0a8-42d9-9381-f13708503ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='winLossReportAllLayout']/div/div/div[2]/form/div[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-control.category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af9e9863-844f-494b-a8dd-1bf687aca2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control category</value>
      <webElementGuid>ec2973e7-fa7e-44f9-a07f-7183d84d09b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    </value>
      <webElementGuid>a99f2034-dcd8-45c7-b7b7-65509e886a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;winLossReportAllLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__head kt-portlet__head--lg&quot;]/div[@class=&quot;kt-portlet__head-toolbar&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group mb-2 mr-2&quot;]/select[@class=&quot;form-control category&quot;]</value>
      <webElementGuid>0d190a11-b400-472f-8033-5ab3ba5cae15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='winLossReportAllLayout']/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>9caeafe9-1c93-418e-9344-dd72dbfcdc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category :'])[1]/following::select[1]</value>
      <webElementGuid>d6d6a166-822c-4a4b-ae12-b7e236b27a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::select[1]</value>
      <webElementGuid>fca7c768-c571-4cf1-8d5e-b5fed025e7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game :'])[1]/preceding::select[1]</value>
      <webElementGuid>bd6ee8ca-3ccd-4d1f-af60-34199ccb1961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range :'])[1]/preceding::select[2]</value>
      <webElementGuid>53b74b48-74c8-4297-9e11-1962ff79f258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>82ea15cc-131d-4e50-a5ba-b11142dc2060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ' or . = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ')]</value>
      <webElementGuid>709c1d0d-c441-4774-9690-a716acec0518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
