<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllEgames</name>
   <tag></tag>
   <elementGuidId>2c69ab41-a9f0-40ed-9ce9-07ef1eb96cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='directWinLossReportLayout']/div/div/div[2]/form/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d636fc92-53c6-4334-92cc-085c2b4030d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control category</value>
      <webElementGuid>6141f0dd-dcc5-46c1-91fd-c26ebb60fedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    </value>
      <webElementGuid>33899499-d203-4b46-8ac5-a070dfa6379e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;directWinLossReportLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__head kt-portlet__head--lg&quot;]/div[@class=&quot;kt-portlet__head-toolbar&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group mb-2 mr-2&quot;]/select[@class=&quot;form-control category&quot;]</value>
      <webElementGuid>aa99cf88-f622-4d72-a56e-5a6fd47a17f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='directWinLossReportLayout']/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>9c418ad7-8dfe-49c3-b4f1-568b3c2be104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category :'])[1]/following::select[1]</value>
      <webElementGuid>24a1d34c-d938-44c7-a1fd-85ca4743c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username :'])[1]/following::select[1]</value>
      <webElementGuid>c5c183ca-4b7e-4390-bb65-12ebddf2b758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game :'])[1]/preceding::select[1]</value>
      <webElementGuid>1e071bef-ea83-459d-abff-2d80c67c7d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range :'])[1]/preceding::select[2]</value>
      <webElementGuid>776a4e9c-6b8f-42fb-ab0d-ce64c278059e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c610efb7-fd70-4a2e-b6fe-25ace3adca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ' or . = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ')]</value>
      <webElementGuid>55c8fe98-f4a2-4040-80ae-a2d4633aec44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
