<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllEgames</name>
   <tag></tag>
   <elementGuidId>ccc8a9f2-a782-4fa7-b558-fc8dafffef53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='winLossReportDirectLayout']/div/div/div[2]/form/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-control.category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e6177ef7-d329-48bc-b62d-25976f917170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control category</value>
      <webElementGuid>17e0ea11-d492-450f-a8a2-9c752a7977f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    </value>
      <webElementGuid>fa8d5a17-2c57-4f51-b5a3-d094e4f54d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;winLossReportDirectLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__head kt-portlet__head--lg&quot;]/div[@class=&quot;kt-portlet__head-toolbar&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group mb-2 mr-2&quot;]/select[@class=&quot;form-control category&quot;]</value>
      <webElementGuid>65b8091e-2748-4adb-8050-34a78008beb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='winLossReportDirectLayout']/div/div/div[2]/form/div/select</value>
      <webElementGuid>ccfee588-003a-4fb4-b8c8-9d5be6fdbfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category :'])[1]/following::select[1]</value>
      <webElementGuid>fa0ea72a-d80f-419a-b821-77ae1d1a827b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Win Loss Report'])[2]/following::select[1]</value>
      <webElementGuid>b9da0aa4-9a97-46ed-938c-4f8477709c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game :'])[1]/preceding::select[1]</value>
      <webElementGuid>94288c3d-0965-456c-bd7c-286690ac4a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range :'])[1]/preceding::select[2]</value>
      <webElementGuid>c700d9ae-ace2-4b52-8e40-0caba5c27346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e4b2d0c5-52c7-47cd-9ed2-202c9bc3bc82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ' or . = '
                            All
                                                            Egames
                                                            Fishing
                                                            Live
                                                            Lottery
                                                            Sport
                                                    ')]</value>
      <webElementGuid>4746668b-b803-4994-8e22-209e14b5ce65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
