<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Block</name>
   <tag></tag>
   <elementGuidId>9aec1878-94aa-4c96-a7cc-ebd369686670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable']/tbody/tr/td[8]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.actionBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b70c5349-05d9-40d0-b0fc-f2688ce5a969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger actionBtn</value>
      <webElementGuid>8ab3bd1f-2572-4bac-9ded-dee38bab8053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d2adbf79-0c75-400a-bc4c-302cd3f9290d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>inactive</value>
      <webElementGuid>b021c78a-fee2-4799-82dd-b3d31ab6b9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>NACWOrGoFsbxbJqg2dwBvcEcBx0Ji1t4Igk3z1w7Dq4eLx35MXciym6hCoveKwDhq658rGB6IPpmaY07EfvvFG8u6IqoYzxOqbuHEPjBKPnCzv5NZDEWrk0w9Ji28HvPjen7D6K63HB2lYtHNLYY9ygedULaIYDulOysYS1xRT4yOx4hEB8F7gzx0RX4n7jy4gxkwyWK</value>
      <webElementGuid>4aba72c0-a9cb-43c6-87fc-2eab8f1d6a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Block</value>
      <webElementGuid>c85ed9a1-b71d-46e6-8491-b9252248ee09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/button[@class=&quot;btn btn-danger actionBtn&quot;]</value>
      <webElementGuid>eb0e7354-4d5f-4452-ba93-f1d7219cbb1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable']/tbody/tr/td[8]/button</value>
      <webElementGuid>e711ab51-d8df-452f-842d-d21438f28063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='active'])[1]/following::button[1]</value>
      <webElementGuid>d34b080f-26de-4440-97e5-af56fd7986a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[1]/following::button[1]</value>
      <webElementGuid>30d0fb06-2d65-4931-b49e-e2c0ea60197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>1e0b5d4a-5c6f-44e1-977c-7aa660e9be66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::button[2]</value>
      <webElementGuid>853b40c2-0c92-4ff3-a2b9-95e9dc3277c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Block']/parent::*</value>
      <webElementGuid>04617b9f-a38d-4e41-b81a-abe3ebf30639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button</value>
      <webElementGuid>c6a72e26-21f0-45f2-aa24-7604f07ba419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Block' or . = 'Block')]</value>
      <webElementGuid>b92285ae-7ec5-47fc-998b-e7c456302adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
