<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Password</name>
   <tag></tag>
   <elementGuidId>aac77c8e-b168-4cb8-b053-5c96646d0c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable']/tbody/tr/td[8]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-warning.editModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>385c0c8f-75ad-4c34-b5df-954476f5e9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning editModal</value>
      <webElementGuid>7b85f470-d2fe-4108-8a1a-8b370add2054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e1c9704e-1702-45ad-89b8-72af885af770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>NACWOrGoFsbxbJqg2dwBvcEcBx0Ji1t4Igk3z1w7Dq4eLx35MXciym6hCoveKwDhq658rGB6IPpmaY07EfvvFG8u6IqoYzxOqbuHEPjBKPnCzv5NZDEWrk0w9Ji28HvPjen7D6K63HB2lYtHNLYY9ygedULaIYDulOysYS1xRT4yOx4hEB8F7gzx0RX4n7jy4gxkwyWK</value>
      <webElementGuid>bb618153-1ad8-4f44-ba7d-b6162aad4323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>miracle8</value>
      <webElementGuid>9c09bae9-e511-4bed-9593-374789e11f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#editModal</value>
      <webElementGuid>ecbce6f9-e7c2-487d-8803-bff6c4ff53d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1997fe0c-e808-4868-a17d-10a943056089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/button[@class=&quot;btn btn-warning editModal&quot;]</value>
      <webElementGuid>0b78afed-8225-4e17-b7c0-b2a7d02fd203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable']/tbody/tr/td[8]/button[3]</value>
      <webElementGuid>4575cac7-9571-4bdc-89d1-3b27bd804b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>ae05d480-8788-49ba-abfa-14554bbe6757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Block'])[1]/following::button[2]</value>
      <webElementGuid>ad47c01c-c1aa-4d47-a51b-07a1ced4d523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>73a1d645-0bfe-4a94-8073-728b8369307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kedou2299'])[1]/preceding::button[2]</value>
      <webElementGuid>a06a2e24-0e06-4230-b2d8-f80c56d7044a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password']/parent::*</value>
      <webElementGuid>280f6838-6f77-4b9f-acde-cc78091b8b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button[3]</value>
      <webElementGuid>077ace00-b7c0-43f9-91f3-bf775aa7c795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>50959249-7b67-4a3e-9226-84f3ff508467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
