<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>24456128-30ff-469f-af0e-4592f705cb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable1']/tbody/tr/td[18]/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.editModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70a5e4d5-0efc-4458-8456-0b29d9b28100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item editModal</value>
      <webElementGuid>214c1997-68c8-46bc-a163-8a61589c9214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e9aa0337-dd6e-430b-af6d-5b6a1911136b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>VqxFXyirFnJbnZi5jpGvnnP3oV7QCFVNN7gNkYF0uGEceYbNDHKG6NS8mlH2vPkUlgJgangvNPnCYIXx8nl4CnnfPIWBqfnMtrDHsrL3sigyvpriVMdYNaGSxfDDM5674bwK8dFnmp3fAqL5SlDq72AcUiFDBkMeXiyhSTCALxpeDNiS0r9HzpIX306XTa5GBTr0rW7b</value>
      <webElementGuid>1c86a112-f637-4711-a578-c40b6533573b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-percentage</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>426e2ffc-467e-4604-9491-25ebaf1a753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>shareholder</value>
      <webElementGuid>4d10fb21-c7f3-47ad-a342-bf4e0a0fbbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>kong long</value>
      <webElementGuid>85ae981d-695e-48fd-a63d-ed001f9a9ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#editModal</value>
      <webElementGuid>cd13ce12-c075-41e6-a337-7c9ed036f8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>12b68f35-abc5-421c-ae18-d527cb595c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[18]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;dropdown-item editModal&quot;]</value>
      <webElementGuid>318c9353-29f1-48f9-b409-ff62c68f6add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable1']/tbody/tr/td[18]/div/div/a[3]</value>
      <webElementGuid>48efc409-a4b6-4bc9-a11e-0d8cbbeb09a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>3ae73f52-bfd5-43d2-8d13-15ab38baf223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stat'])[1]/following::a[1]</value>
      <webElementGuid>25a0063c-a3a2-4272-bbbb-c15ab4181d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::a[2]</value>
      <webElementGuid>6334ee48-0c9f-4998-96ce-d97445f59a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Block'])[1]/preceding::a[2]</value>
      <webElementGuid>b97f6c0a-8d9c-4c7b-8e71-6e924dd42cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records'])[1]/preceding::a[3]</value>
      <webElementGuid>8bb25db6-6ade-4214-8122-4c937cbbfc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>c363af78-c214-4079-9f32-bf442528830d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>0c8797ea-fd6a-45f0-a406-fc007845f7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>5f37b1df-14fc-49c3-a31d-f81916f5674a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
