<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_7</name>
   <tag></tag>
   <elementGuidId>95a7798d-3966-4a52-af8a-2ef1c01a002d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sortable']/li[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>30bda3bd-925d-4614-a025-c912815552fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-unstyled bg-light border dropper p-3 ui-sortable-handle</value>
      <webElementGuid>e1267092-f084-4ca3-8759-2b819976165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 7
                            </value>
      <webElementGuid>7b6b2a50-ab52-4e0d-88ef-abfe7cd9d031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sortable&quot;)/li[@class=&quot;list-unstyled bg-light border dropper p-3 ui-sortable-handle&quot;]</value>
      <webElementGuid>2728140b-dc02-4923-9d9c-0e76c35b534d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sortable']/li[8]</value>
      <webElementGuid>a8f49a57-b187-46f5-8c2a-163628948472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 6'])[1]/following::li[1]</value>
      <webElementGuid>182d0442-6691-4d7e-9f98-e321ab358757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 5'])[1]/following::li[2]</value>
      <webElementGuid>252e48d1-081b-47c5-9573-9560ae9e2683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to VIP List'])[1]/preceding::li[1]</value>
      <webElementGuid>9e93b2c3-51fb-4da6-bf41-6db0838705b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::li[1]</value>
      <webElementGuid>5ae6938f-2d18-40ff-bcc1-10ddd00efeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[8]</value>
      <webElementGuid>8b4ed706-c1c0-4355-a8b2-4bc0abafb8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                 7
                            ' or . = '
                                 7
                            ')]</value>
      <webElementGuid>fc3fd548-aeb0-4f75-af27-bdde8c1e07b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
