<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIP 2</name>
   <tag></tag>
   <elementGuidId>ae6b19ff-6b45-4849-954d-a188057112dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drag-id-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drag-id-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3459efa-839d-433e-901f-695892877455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VIP 2</value>
      <webElementGuid>09916366-d6e2-4238-993b-90134a519389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vip-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>df0cd014-ea84-4637-b474-5cd3c674eff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drop-id</name>
      <type>Main</type>
      <value>drop-id-2</value>
      <webElementGuid>5f2e10ce-e408-437b-978e-f085a1b136ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-image</value>
      <webElementGuid>1e3de8b9-808c-4292-8311-328faa664f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-id-3</value>
      <webElementGuid>fee19082-2745-4d3f-b7bf-4f9975b5da00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cf56ac9-0b5b-48c1-bfe3-1b2b457f5107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VIP 2</value>
      <webElementGuid>9063f17b-ca43-4c7d-a05b-fa20b1cf09f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-id-3&quot;)</value>
      <webElementGuid>594c5899-78a7-4d40-a740-9c64201ec86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drag-id-3']</value>
      <webElementGuid>1f49e847-bfbe-4510-a416-f79bafbf16ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sortable']/li[3]/span</value>
      <webElementGuid>5674637b-ae34-4387-95d4-9910b5b227d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 1'])[1]/following::span[1]</value>
      <webElementGuid>addd6392-a2de-4c3f-b17f-82c76a87c760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 0'])[1]/following::span[2]</value>
      <webElementGuid>9eb3d4f6-75c5-4401-8c5b-874102b33e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 3'])[1]/preceding::span[1]</value>
      <webElementGuid>82adbf2e-7d2d-4fae-94a8-f997cb5f98bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 4'])[1]/preceding::span[2]</value>
      <webElementGuid>6d5385e5-77db-41f3-a71a-de1dc697e9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIP 2']/parent::*</value>
      <webElementGuid>6e238511-1eed-4e72-b82e-c20a2675113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>bfbcbef2-1c9a-46b7-b1e2-40e670340e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'VIP 2' and @id = 'drag-id-3' and (text() = ' VIP 2' or . = ' VIP 2')]</value>
      <webElementGuid>32e166a7-f2a2-444a-b3dd-5d579573bd30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
