<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIP THB 1</name>
   <tag></tag>
   <elementGuidId>5bbd4b4b-919d-44c4-823c-585a5071e6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drag-id-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drag-id-25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9cda989-ee1b-4828-b16f-53e254cb6e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VIP THB 1</value>
      <webElementGuid>08941de2-14a9-4f36-9835-1dc943c71c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vip-id</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>bcdbaacd-b00b-4211-8fc5-36b9b48bfe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drop-id</name>
      <type>Main</type>
      <value>drop-id-1</value>
      <webElementGuid>c2251340-9394-4812-8ac2-6bf68ed0314c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-image</value>
      <webElementGuid>14845de0-c1aa-444c-b8f0-674c7803a9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-id-25</value>
      <webElementGuid>6b73da1f-a85f-4289-a9db-1f3901e3d2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>068e7b93-4947-4c4f-80c4-e3d132e52b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VIP THB 1</value>
      <webElementGuid>fbb7dd80-c8a6-4b75-adf9-13c9a375bfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-id-25&quot;)</value>
      <webElementGuid>f3e2d8e6-1875-4938-837b-b0cac18875f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drag-id-25']</value>
      <webElementGuid>f2ffdf3b-7f37-445c-bb1d-a5fd02feba6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sortable']/li[2]/span</value>
      <webElementGuid>1a6c9f03-8767-4322-ab1b-02d684e63392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP THB 0'])[1]/following::span[1]</value>
      <webElementGuid>b7c53332-691c-4aa4-bfc4-3c819563ee3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='section'])[1]/following::span[2]</value>
      <webElementGuid>43239781-0eef-4c5c-8254-df92b3ac2ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP THB 2'])[1]/preceding::span[1]</value>
      <webElementGuid>27846038-8884-41df-9037-3c29bf740ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP THB 3'])[1]/preceding::span[2]</value>
      <webElementGuid>c77c11ff-4547-4a51-8302-68b771bb8493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIP THB 1']/parent::*</value>
      <webElementGuid>84b0cf54-b5d8-414b-9cdb-46eafa60af23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/span</value>
      <webElementGuid>245b5f1c-b04f-4ad8-9453-e9d5bec8bebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'VIP THB 1' and @id = 'drag-id-25' and (text() = ' VIP THB 1' or . = ' VIP THB 1')]</value>
      <webElementGuid>0709fde4-4d33-4d1a-80c4-c11544ac1ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
