<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIP 3</name>
   <tag></tag>
   <elementGuidId>40a730c7-fccf-47ae-a4c8-4e6da25bae15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drag-id-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drag-id-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e064a11-35d0-448f-8ad5-27a6f1f3135d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VIP 3</value>
      <webElementGuid>73712e3d-fd76-414d-8600-2f05b9ed2e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vip-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b3bc3c66-231d-4509-b9e4-6ab5b00ff0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drop-id</name>
      <type>Main</type>
      <value>drop-id-3</value>
      <webElementGuid>a8da6f34-02ba-4752-8846-ab27c6254fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-image</value>
      <webElementGuid>f673d6e3-5d39-4e42-a7ac-29c72b370016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-id-4</value>
      <webElementGuid>518cc09c-5c57-42a6-9417-df15e14946c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f34f7f09-b155-4595-bc84-c0847393ca04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VIP 3</value>
      <webElementGuid>691dd5ca-4ef8-4de7-9b36-6ddf435cc2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-id-4&quot;)</value>
      <webElementGuid>410ebccb-829d-40a6-85c9-4b0d84a046cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drag-id-4']</value>
      <webElementGuid>6460efe1-7731-4c3f-be03-12d8d3664c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sortable']/li[4]/span</value>
      <webElementGuid>d4827556-9f9e-4c58-b126-a6f2d868ab29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 2'])[1]/following::span[1]</value>
      <webElementGuid>dac4f990-bbfa-43a3-a20e-52b910970951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 1'])[1]/following::span[2]</value>
      <webElementGuid>cc5e38cf-9c02-4016-8ad1-f0804a81e880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 4'])[1]/preceding::span[1]</value>
      <webElementGuid>5ae3702c-6210-4ebd-8ed8-05ff3ffcd462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP 5'])[1]/preceding::span[2]</value>
      <webElementGuid>003ae22a-2f80-49be-9071-98ad35adfbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIP 3']/parent::*</value>
      <webElementGuid>dbba0c57-a223-45d8-83ca-6b0e2a01daf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>55bdcf94-4926-42b9-ab74-5e24df9993b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'VIP 3' and @id = 'drag-id-4' and (text() = ' VIP 3' or . = ' VIP 3')]</value>
      <webElementGuid>aa8c3371-0d43-4e9a-8521-a0f866e4dd3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
