<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIP THB 0</name>
   <tag></tag>
   <elementGuidId>376ac0a1-b117-40d6-a603-65aa2049ef98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#drag-id-24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drag-id-24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9a986f6-5e22-41ac-a3a0-169cdafd652c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VIP THB 0</value>
      <webElementGuid>c41fa357-7329-4f63-8bd4-93df2c3d98be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vip-id</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>78189e58-0837-4832-8e90-1ee3052c6d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drop-id</name>
      <type>Main</type>
      <value>drop-id-0</value>
      <webElementGuid>d69422ab-784d-481f-b14a-3ba184ac972c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-image</value>
      <webElementGuid>e67597d5-e505-41b7-8429-13e64612d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-id-24</value>
      <webElementGuid>d91e567a-5ee7-46fe-be72-224c46f86214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fcf9068-8f04-4819-b426-9d738a53b4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> VIP THB 0</value>
      <webElementGuid>9895b2c3-b85c-4d26-b254-df2330974347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-id-24&quot;)</value>
      <webElementGuid>10625e87-67ba-4345-bd77-19d8772c6a3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drag-id-24']</value>
      <webElementGuid>4741f6c3-6526-4b93-bde7-3dcbf1634cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sortable']/li/span</value>
      <webElementGuid>90454760-f9fa-4b8e-9750-dc2730aa86a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='section'])[1]/following::span[1]</value>
      <webElementGuid>181cde35-239c-46ab-827e-26955fa25123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drag'])[1]/following::span[1]</value>
      <webElementGuid>d2d714ac-3c2e-4c1f-ac7c-07bf7788f290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP THB 1'])[1]/preceding::span[1]</value>
      <webElementGuid>22fbd357-975f-43d8-81dd-97994ce9fd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP THB 2'])[1]/preceding::span[2]</value>
      <webElementGuid>12602418-feec-4871-92d7-f7c17dcfeefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIP THB 0']/parent::*</value>
      <webElementGuid>5abb0438-76df-4577-ae5b-95f640a7fe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/span</value>
      <webElementGuid>e9b9b861-a3a6-48c8-bb75-b63c44911cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'VIP THB 0' and @id = 'drag-id-24' and (text() = ' VIP THB 0' or . = ' VIP THB 0')]</value>
      <webElementGuid>f59a6f43-670e-4973-b0f5-1cf6c4d249ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
