<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Previous</name>
   <tag></tag>
   <elementGuidId>150a17f0-725f-445c-97f5-941fbce964be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable_previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='datatable_previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4fd42141-7658-4214-9bbd-8a9223847324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item previous disabled</value>
      <webElementGuid>fc81d0f5-d3a8-41f8-8a8d-8c804c01ef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatable_previous</value>
      <webElementGuid>d69772df-faa2-4f3e-9622-b54a4277b565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>a40f20dd-97c7-4b53-ba95-7497b086d4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_previous&quot;)</value>
      <webElementGuid>e10de131-a66c-493f-971e-a578cce7dd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='datatable_previous']</value>
      <webElementGuid>170abaab-0a57-42fe-9f50-8bfd7f40ac81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatable_paginate']/ul/li</value>
      <webElementGuid>ce9f4e8d-d39d-4e02-992b-b75bf6ecb6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 8 of 8 entries'])[1]/following::li[1]</value>
      <webElementGuid>f808c0b7-2b07-42fe-94b3-1e09f0bbff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LK Point Stake'])[8]/following::li[1]</value>
      <webElementGuid>73d729c0-2ed7-41e5-8488-d7a74926c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create VIP'])[2]/preceding::li[3]</value>
      <webElementGuid>72185ea4-5820-4d0b-9b25-bd9faef95cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP Tier Name'])[1]/preceding::li[3]</value>
      <webElementGuid>5661a387-a64e-49da-8d9f-004e26781d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li</value>
      <webElementGuid>009d27ae-31a9-446c-ab71-d1079c2135d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'datatable_previous' and (text() = 'Previous' or . = 'Previous')]</value>
      <webElementGuid>b10bd4e9-3194-489b-822f-69bbfa125ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
