<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllMYR</name>
   <tag></tag>
   <elementGuidId>a2503080-ef72-47ff-87b6-8588e1a8ec8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control.currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='currencyConversionsLayout']/div/div/form/div[3]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a13b0485-960c-4998-830a-02a7d13ce7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control currency</value>
      <webElementGuid>5a5c4dd8-ec82-450c-ae31-4ce2dfa31ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        All
                                                    MYR
                                                        THB
                                                        USD
                                                        IDR
                                                        MMK
                                                        RMB
                                                </value>
      <webElementGuid>d0a2576e-4e18-4320-86d4-9a060c2c08db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currencyConversionsLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__head kt-portlet__head--lg&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group mb-2 mr-2&quot;]/select[@class=&quot;form-control currency&quot;]</value>
      <webElementGuid>984d4cd1-81dd-4f1c-a082-cd749516496a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currencyConversionsLayout']/div/div/form/div[3]/select</value>
      <webElementGuid>6dd6305d-850f-421a-bcac-28efdbc076a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::select[1]</value>
      <webElementGuid>f2d5af69-3111-411f-bad6-0aaf466a5d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Type'])[1]/following::select[2]</value>
      <webElementGuid>811500cf-f541-4a57-abb1-2f5fb6ef917e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datetime Range'])[1]/preceding::select[1]</value>
      <webElementGuid>b61c9a33-2c86-4119-9d8a-53416c7db718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::select[1]</value>
      <webElementGuid>589d83af-13ed-410f-8a3d-07a21afcfd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>5eda3a7e-6146-42c0-a022-ffbe1a61154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                        All
                                                    MYR
                                                        THB
                                                        USD
                                                        IDR
                                                        MMK
                                                        RMB
                                                ' or . = '
                        All
                                                    MYR
                                                        THB
                                                        USD
                                                        IDR
                                                        MMK
                                                        RMB
                                                ')]</value>
      <webElementGuid>a5c9d3fa-aefb-4ecc-8a37-b9129f59e5d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
