<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Profit</name>
   <tag></tag>
   <elementGuidId>66c8ec97-8334-45c4-9f2a-2fc95d91ffbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='instantSummaryLayout']/div/div[2]/table/thead/tr/th[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(13)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>7f7df1e8-2ae8-4f1d-ae8a-d2cfbe91edc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profit</value>
      <webElementGuid>309ce3ef-72f3-4b0d-b014-bdf688d40f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instantSummaryLayout&quot;)/div[@class=&quot;kt-portlet kt-portlet--mobile&quot;]/div[@class=&quot;kt-portlet__body&quot;]/table[@class=&quot;table table-striped- table-bordered table-hover table-checkable table-responsive w-100 d-block d-md-table datatableCustomTop&quot;]/thead[1]/tr[1]/th[13]</value>
      <webElementGuid>783c0e41-05e3-4ee3-a0f4-61c0ab53a7b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='instantSummaryLayout']/div/div[2]/table/thead/tr/th[13]</value>
      <webElementGuid>b49c790f-b05a-4688-b8c0-e2fba1b0ca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game'])[2]/following::th[1]</value>
      <webElementGuid>a1fd9ec6-d4f3-4dae-a29d-219af24b2665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest'])[2]/following::th[2]</value>
      <webElementGuid>a69faeb0-2c86-478f-a9d4-d9ecf8fb9ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::th[1]</value>
      <webElementGuid>72952838-bfe2-4507-9dce-2f76cdda2346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::th[1]</value>
      <webElementGuid>bc5f9a75-7fe7-4dd2-85ea-e5d38f7f4c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profit']/parent::*</value>
      <webElementGuid>f6c0ff77-ad8e-4b98-805e-40bee4add9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[13]</value>
      <webElementGuid>b64ae006-8aeb-4319-b23c-046bd6a9a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Profit' or . = 'Profit')]</value>
      <webElementGuid>8cdd7bdd-0ca5-41f4-8eb1-8dfb03bcea2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
