<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_dp1689253506982</name>
   <tag></tag>
   <elementGuidId>d6017c46-1100-4dfa-8b7b-2093218f8c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1689253506982</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1689253506982']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64d38faf-28bd-4798-8b0a-390772b0e31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8319ba35-ecd6-4dd9-8eb6-47440193d291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker date hasDatepicker</value>
      <webElementGuid>29f384e4-416c-4d87-baab-e52273ac7709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>13-07-2023</value>
      <webElementGuid>df3b4d47-8646-4c4d-acbc-45bc6e64cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date</value>
      <webElementGuid>e96a5743-d3ee-4761-9553-532c4e51ff14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1689253506982</value>
      <webElementGuid>35723ce3-a4f9-4a9c-856d-b5bdfb510269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1689253506982&quot;)</value>
      <webElementGuid>8fa0b825-7269-42a2-97c5-43a09f2d16e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1689253506982']</value>
      <webElementGuid>b5483d11-7072-470c-9355-bb0d17b171cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settlementListLayout']/div/div/div[2]/form/div/input</value>
      <webElementGuid>c5d1a738-fc3a-4041-908b-e8818a16c342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>30088a24-b947-4444-83e6-cc190b2b174b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Select Date' and @id = 'dp1689253506982']</value>
      <webElementGuid>df0a1dd2-d0f6-4ae3-8bf6-b238af2cc1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
