<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Normal (90130) Percentage</name>
   <tag></tag>
   <elementGuidId>1289962a-6ac4-4e7d-81c1-71b8cac33468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;shareholderType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='shareholderType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d3db1ed1-93c6-4196-a6d9-8a1ce4b752d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shareholderType</value>
      <webElementGuid>d074dd64-c278-497d-8bf2-f28e19539fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86477d80-0d69-43cb-97b2-80a60e6b2502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Normal (90/130)
                                Percentage
                        </value>
      <webElementGuid>37cdbee7-1b56-44a3-a36f-c5b1d10a2747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareholderCreateLayout&quot;)/div[@class=&quot;kt-portlet__body&quot;]/div[@class=&quot;kt-section kt-section--first&quot;]/form[@class=&quot;kt-form&quot;]/div[@class=&quot;kt-section__body&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9 col-xl-6&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ac1ca4ee-e408-47f0-ad3c-2c051c98d347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='shareholderType']</value>
      <webElementGuid>c3764a42-64fa-4f3e-b3da-927c4b99d219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shareholderCreateLayout']/div/div/form/div/div[8]/div/select</value>
      <webElementGuid>24f2cb7b-d0a9-45c7-8ac8-1077911e1166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Type'])[2]/following::select[1]</value>
      <webElementGuid>ef3b64bc-49f3-4e99-b0f2-1dde8003c96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Type'])[1]/following::select[2]</value>
      <webElementGuid>472a100b-fa94-44c9-bb01-279c4da1eca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[2]/preceding::select[1]</value>
      <webElementGuid>ae19c398-f8f2-4dcc-86d8-cff3b43ecebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/preceding::select[1]</value>
      <webElementGuid>43a86e83-64e5-4ccf-9ffd-9f257bc63e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>afd74820-7b7c-48d4-b6be-e01a9fda9d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'shareholderType' and (text() = '
                                Normal (90/130)
                                Percentage
                        ' or . = '
                                Normal (90/130)
                                Percentage
                        ')]</value>
      <webElementGuid>a9c19d20-ea2e-403f-aa0b-39017ffc186c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
